### ISSUE TITLE
data

### ISSUE THREAD

**Issue by OnePl3** [d9n13lt4n/timegan-pytorch#2]
Is it convenient to describe the composition of your stock.csv data, I don't quite understand the Time output in your data_loading section.

**Comment by ghost** [comment]
The `stock.csv` dataset is derived after following the preprocessing methods from the original TimeGAN implementation.  Each `idx` corresponds to a sample, and the `time` output denotes the sequence length for each sample. In the case of the `stock.csv` dataset, all values are would be the max sequence length. This would be used in `lengths` argument for the `pack_padded_sequence` in the forward pass of each network. 

The `time` variable is mainly used for modeling sequences of dynamic length. Although it is not used for the given datasets, I decided to add it due to it being implemented in the original code. You could refer to the original implementation here: [Yoon et al., 2019](https://github.com/jsyoon0823/TimeGAN).

**Comment by OnePl3** [comment]
Thank you for your answer, can I understand that this is a sample of different lengths in the same class of data?Yoon's idea is to directly slice a longer data according to a certain length, you are dealing with your own shu'j that has already been sliced.

**Comment by OnePl3** [comment]
Thank you for your answer, can I understand that this is a sample of different lengths in the same class of data?Yoon's idea is to directly slice a longer data according to a certain length, you are dealing with your own shu'j that has already been sliced.

**Comment by OnePl3** [comment]
Thank you for your answer, can I understand that this is a sample of different lengths in the same class of data, Yoon's idea is to directly slice a longer data according to a certain length, you are dealing with your own already sliced data.

**Comment by ghost** [comment]
In short: 
1. The samples are of equal length. 
2. Yes, the data within the `.csv` file is already sliced. 

I said that the preprocessing method is similar to Yoon et al's is because the dataset was actually obtained from a competition they organized. So, the (max) sequence length might not be the same as their original code-base, but the preprocessing procedure is definitely the same. 

You could refer to the baseline code for the competition I mentioned here: [hide-and-seek](https://github.com/jsyoon0823/hide-and-seek). 

I hope my explanation is clear. Please feel free to ask any questions regarding the code, it's a little bit messy. Cheers.

**Comment by OnePl3** [comment]
Thank you again for your prompt reply. I have a better understanding of your project. For you to say those attention points, I will seriously consult! HHH brother I think this code is quite good! I hope you enjoy your life, and I will trouble you again if I have any questions!---- Replied Message ***@***.***>Date11/18/2021 22:18 ***@***.***> ***@***.******@***.***>SubjectRe: [d9n13lt4n/timegan-pytorch] data (Issue #2)
In short:

The samples are of equal length.
Yes, the data within the .csv file is already sliced.

I said that the preprocessing method is similar to Yoon et al's is because the dataset was actually obtained from a competition they organized. So, the (max) sequence length might not be the same as their original code-base, but the preprocessing procedure is definitely the same.
You could refer to the baseline code for the competition I mentioned here: hide-and-seek.
I hope my explanation is clear. Please feel free to ask any questions regarding the code, it's a little bit messy. Cheers.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/d9n13lt4n/timegan-pytorch/issues/2#issuecomment-972907062",
"url": "https://github.com/d9n13lt4n/timegan-pytorch/issues/2#issuecomment-972907062",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by OnePl3** [comment]
Thank you again for your prompt reply.

 I have a better understanding of your project.

For you to say those attention points, I will seriously consult! 

HHH brother I think this code is quite good! 

I hope you enjoy your life, and I will trouble you again if I have any questions!
